import React, { useState } from 'react';
import { 
  Link2, 
  Sparkles, 
  CheckCircle2, 
  AlertTriangle, 
  Download, 
  Copy, 
  Check, 
  Plus, 
  Globe, 
  ExternalLink,
  ShieldCheck,
  Zap,
  TrendingUp,
  Mail,
  Building2,
  FileCode,
  Search
} from 'lucide-react';
import type { ClientProject, BacklinkItem, OutreachOpportunity } from '../../types/seo';

interface BacklinkGeneratorProps {
  client: ClientProject;
  backlinks: BacklinkItem[];
  outreachOps: OutreachOpportunity[];
  onAddBacklink: (backlink: BacklinkItem) => void;
  onUpdateOutreachStatus?: (id: string, status: OutreachOpportunity['status']) => void;
}

export const BacklinkGenerator: React.FC<BacklinkGeneratorProps> = ({
  client,
  backlinks,
  outreachOps,
  onAddBacklink
}) => {
  const [selectedTab, setSelectedTab] = useState<'generator' | 'profile' | 'outreach' | 'disavow'>('generator');
  const [isGenerating, setIsGenerating] = useState(false);
  const [progress, setProgress] = useState(0);
  const [statusText, setStatusText] = useState('');
  const [filterCategory, setFilterCategory] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState('');

  // Form state for backlink generation
  const [targetUrl, setTargetUrl] = useState(`https://${client.domain}`);
  const [anchorText, setAnchorText] = useState(`${client.name} official telehealth`);
  const [selectedCategory, setSelectedCategory] = useState<BacklinkItem['category']>('Tech Directory');
  const [quantity, setQuantity] = useState<number>(5);

  // Email pitch generator state
  const [activePitch, setActivePitch] = useState<{ op: OutreachOpportunity; email: string } | null>(null);
  const [copied, setCopied] = useState(false);

  // Filtered backlinks
  const clientBacklinks = backlinks.filter(b => b.clientId === client.id || !b.clientId);
  const filteredBacklinks = clientBacklinks.filter(b => {
    const matchesCat = filterCategory === 'all' || 
      (filterCategory === 'toxic' ? b.toxicityScore > 50 : b.category.toLowerCase().includes(filterCategory.toLowerCase()));
    const matchesSearch = b.referringDomain.toLowerCase().includes(searchQuery.toLowerCase()) || 
      b.anchorText.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCat && matchesSearch;
  });

  const totalBacklinks = clientBacklinks.length > 0 ? client.backlinksCount : 1250;
  const dofollowCount = clientBacklinks.filter(b => b.linkType === 'dofollow').length;
  const dofollowPct = clientBacklinks.length > 0 ? Math.round((dofollowCount / clientBacklinks.length) * 100) : 84;
  const toxicCount = clientBacklinks.filter(b => b.toxicityScore > 50).length;

  // Run Auto Backlink Generator Simulation
  const handleStartAutoGenerator = () => {
    setIsGenerating(true);
    setProgress(10);
    setStatusText('Analyzing client domain authority & high-DA directories...');

    setTimeout(() => {
      setProgress(35);
      setStatusText('Pinging Web 2.0 indexers (DA 85-95 platforms)...');
    }, 1000);

    setTimeout(() => {
      setProgress(65);
      setStatusText('Injecting anchor text & generating schema citations...');
    }, 2000);

    setTimeout(() => {
      setProgress(90);
      setStatusText('Notifying Googlebot & Bingbot fast indexers...');
    }, 3000);

    setTimeout(() => {
      setProgress(100);
      setIsGenerating(false);
      
      // Create generated backlink item
      const newBL: BacklinkItem = {
        id: `bl-${Date.now()}`,
        clientId: client.id,
        referringDomain: selectedCategory === 'Tech Directory' ? 'crunchbase.com' : 
                         selectedCategory === 'Web 2.0' ? 'medium.com' : 
                         selectedCategory === 'Edu/Gov Citation' ? 'nih.gov.citation-index.net' : 
                         selectedCategory === 'Press Release' ? 'digitaljournal.com' : 'healthtechdaily.org',
        referringPageTitle: `${client.name} - Verified High-DA ${selectedCategory} Profile`,
        targetUrl,
        domainRating: Math.floor(Math.random() * 15) + 82, // High DA 82-96
        anchorText,
        linkType: 'dofollow',
        category: selectedCategory,
        status: 'pinged',
        toxicityScore: 0,
        createdAt: new Date().toISOString().split('T')[0]
      };

      onAddBacklink(newBL);
      alert(`Success! Generated and pinged ${quantity} high-DA ${selectedCategory} backlinks for ${client.domain}!`);
    }, 4000);
  };

  // Generate disavow content
  const disavowContent = `# Google Search Console Disavow File for ${client.domain}
# Generated by RankPulse Pro - Toxic Link Remediation
# Date: ${new Date().toISOString().split('T')[0]}

${clientBacklinks.filter(b => b.toxicityScore > 50).map(b => `domain:${b.referringDomain}`).join('\n') || '# No toxic links detected!'}
`;

  const handleDownloadDisavow = () => {
    const element = document.createElement('a');
    const file = new Blob([disavowContent], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `disavow-${client.domain.replace(/\./g, '-')}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleGeneratePitch = (op: OutreachOpportunity) => {
    const pitch = `Subject: Guest Contribution / Resource Inclusion for ${op.websiteName}

Hi ${op.websiteName} Editorial Team,

I've been following your articles on ${op.niche} and loved your recent piece. 

I'm the SEO Content Director for ${client.name} (${client.domain}). We're publishing an in-depth, data-backed guide on "${op.suggestedTopic}". 

Given your readers' interest in ${op.niche}, I thought this would be a fantastic fit for a guest contribution or editorial link reference. We can include custom infographics and original survey data.

Here is the reference anchor target we recommend:
Anchor Text: "${anchorText || client.name}"
Target Link: https://${client.domain}

Would you be open to reviewing a draft this week?

Best regards,
SEO Growth Team at ${client.name}
`;
    setActivePitch({ op, email: pitch });
    setCopied(false);
  };

  const handleCopyPitch = () => {
    if (activePitch) {
      navigator.clipboard.writeText(activePitch.email);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="space-y-6">
      
      {/* Top Banner */}
      <div className="bg-gradient-to-r from-blue-950 via-slate-900 to-indigo-950 p-6 rounded-2xl border border-blue-500/20 shadow-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2 mb-2">
            <span className="p-2 bg-blue-500/20 text-blue-400 rounded-lg">
              <Link2 className="w-5 h-5" />
            </span>
            <h1 className="text-2xl font-bold text-white tracking-tight">
              High-DA Backlink Generator & Authority Engine
            </h1>
          </div>
          <p className="text-sm text-slate-300">
            Generate high-authority dofollow backlinks, submit high-DA citations, execute automated email outreach, and clean toxic PBN links for <span className="font-semibold text-white">{client.domain}</span>.
          </p>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={() => setSelectedTab('generator')}
            className={`px-4 py-2 rounded-xl text-xs font-semibold flex items-center space-x-2 transition ${
              selectedTab === 'generator'
                ? 'bg-gradient-to-r from-indigo-600 to-blue-600 text-white shadow-md shadow-indigo-600/30'
                : 'bg-slate-800/80 text-slate-300 hover:bg-slate-800'
            }`}
          >
            <Zap className="w-4 h-4" />
            <span>Auto Submitter</span>
          </button>
          <button
            onClick={() => setSelectedTab('profile')}
            className={`px-4 py-2 rounded-xl text-xs font-semibold flex items-center space-x-2 transition ${
              selectedTab === 'profile'
                ? 'bg-gradient-to-r from-indigo-600 to-blue-600 text-white shadow-md shadow-indigo-600/30'
                : 'bg-slate-800/80 text-slate-300 hover:bg-slate-800'
            }`}
          >
            <Globe className="w-4 h-4" />
            <span>Link Profile ({clientBacklinks.length})</span>
          </button>
          <button
            onClick={() => setSelectedTab('outreach')}
            className={`px-4 py-2 rounded-xl text-xs font-semibold flex items-center space-x-2 transition ${
              selectedTab === 'outreach'
                ? 'bg-gradient-to-r from-indigo-600 to-blue-600 text-white shadow-md shadow-indigo-600/30'
                : 'bg-slate-800/80 text-slate-300 hover:bg-slate-800'
            }`}
          >
            <Mail className="w-4 h-4" />
            <span>AI Outreach</span>
          </button>
        </div>
      </div>

      {/* Domain Authority & Link Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-slate-900/90 p-4 rounded-xl border border-slate-800 flex items-center justify-between">
          <div>
            <p className="text-xs text-slate-400 font-medium">Domain Rating (DR)</p>
            <h3 className="text-2xl font-bold text-white mt-1">{client.domainRating} <span className="text-xs text-slate-400 font-normal">/ 100</span></h3>
            <p className="text-[11px] text-emerald-400 font-medium mt-1 flex items-center">
              <TrendingUp className="w-3 h-3 mr-1" /> High Authority
            </p>
          </div>
          <div className="p-3 bg-blue-500/10 text-blue-400 rounded-xl">
            <Building2 className="w-6 h-6" />
          </div>
        </div>

        <div className="bg-slate-900/90 p-4 rounded-xl border border-slate-800 flex items-center justify-between">
          <div>
            <p className="text-xs text-slate-400 font-medium">Total Active Backlinks</p>
            <h3 className="text-2xl font-bold text-white mt-1">{totalBacklinks.toLocaleString()}</h3>
            <p className="text-[11px] text-indigo-400 font-medium mt-1">312 Referring Domains</p>
          </div>
          <div className="p-3 bg-indigo-500/10 text-indigo-400 rounded-xl">
            <Link2 className="w-6 h-6" />
          </div>
        </div>

        <div className="bg-slate-900/90 p-4 rounded-xl border border-slate-800 flex items-center justify-between">
          <div>
            <p className="text-xs text-slate-400 font-medium">Dofollow Link Ratio</p>
            <h3 className="text-2xl font-bold text-white mt-1">{dofollowPct}%</h3>
            <p className="text-[11px] text-emerald-400 font-medium mt-1">16% Nofollow Balanced</p>
          </div>
          <div className="p-3 bg-emerald-500/10 text-emerald-400 rounded-xl">
            <ShieldCheck className="w-6 h-6" />
          </div>
        </div>

        <div className="bg-slate-900/90 p-4 rounded-xl border border-slate-800 flex items-center justify-between">
          <div>
            <p className="text-xs text-slate-400 font-medium">Toxic Spam Score</p>
            <h3 className="text-2xl font-bold text-rose-400 mt-1">{toxicCount > 0 ? `${toxicCount} Bad Links` : 'Clean (0%)'}</h3>
            <button 
              onClick={() => setSelectedTab('disavow')} 
              className="text-[11px] text-amber-400 hover:underline font-medium mt-1 block"
            >
              Export Disavow File &rarr;
            </button>
          </div>
          <div className="p-3 bg-rose-500/10 text-rose-400 rounded-xl">
            <AlertTriangle className="w-6 h-6" />
          </div>
        </div>
      </div>

      {/* TAB 1: AUTO BACKLINK GENERATOR */}
      {selectedTab === 'generator' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          
          {/* Main Submission Form */}
          <div className="lg:col-span-2 bg-slate-900/90 p-6 rounded-2xl border border-slate-800 space-y-6">
            <div>
              <h2 className="text-lg font-bold text-white flex items-center space-x-2">
                <Sparkles className="w-5 h-5 text-indigo-400" />
                <span>1-Click Auto High-DA Backlink Submitter</span>
              </h2>
              <p className="text-xs text-slate-400 mt-1">
                Instantly submit client URLs to high Domain Authority (DA 80+) tech directories, Web 2.0 platforms, press release syndicates, and educational research indexers.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1.5">Target Client Landing Page URL</label>
                <input
                  type="url"
                  value={targetUrl}
                  onChange={(e) => setTargetUrl(e.target.value)}
                  placeholder="https://clientdomain.com/landing-page"
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-indigo-500"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1.5">Target Keyword Anchor Text</label>
                <input
                  type="text"
                  value={anchorText}
                  onChange={(e) => setAnchorText(e.target.value)}
                  placeholder="e.g. virtual doctor consultation online"
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-indigo-500"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1.5">Backlink Platform Category</label>
                <select
                  value={selectedCategory}
                  onChange={(e) => setSelectedCategory(e.target.value as BacklinkItem['category'])}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-indigo-500"
                >
                  <option value="Tech Directory">Tech Directory (Crunchbase, ProductHunt, Clutch - DA 88+)</option>
                  <option value="Web 2.0">Web 2.0 Blogs (Medium, Substack, Dev.to - DA 92+)</option>
                  <option value="Edu/Gov Citation">Edu/Gov Research Indexers (NIH, Gov Open Data - DA 95+)</option>
                  <option value="Press Release">Press Release Syndicate (DigitalJournal, PR Newswire - DA 85+)</option>
                  <option value="Niche Blog">Niche Guest Blog Index (Health, Tech, E-Com - DA 75+)</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1.5">Quantity of Backlinks to Create</label>
                <select
                  value={quantity}
                  onChange={(e) => setQuantity(Number(e.target.value))}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-indigo-500"
                >
                  <option value={5}>5 Verified High-DA Backlinks</option>
                  <option value={10}>10 Verified High-DA Backlinks</option>
                  <option value={25}>25 High-DA Backlinks (Recommended)</option>
                  <option value={50}>50 Authority Backlinks Sprint</option>
                </select>
              </div>
            </div>

            {/* Generator Action Button */}
            <div className="pt-2">
              <button
                onClick={handleStartAutoGenerator}
                disabled={isGenerating}
                className="w-full py-3.5 bg-gradient-to-r from-indigo-600 via-blue-600 to-emerald-600 hover:from-indigo-500 hover:to-emerald-500 text-white font-bold text-sm rounded-xl shadow-lg shadow-indigo-600/30 flex items-center justify-center space-x-2 transition disabled:opacity-50"
              >
                {isGenerating ? (
                  <>
                    <Zap className="w-5 h-5 animate-spin" />
                    <span>Executing High-DA Submissions ({progress}%)...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-5 h-5" />
                    <span>Auto-Generate & Submit {quantity} Backlinks Now</span>
                  </>
                )}
              </button>
            </div>

            {/* Live Generation Progress Bar */}
            {isGenerating && (
              <div className="bg-slate-950 p-4 rounded-xl border border-indigo-500/30 space-y-2">
                <div className="flex items-center justify-between text-xs">
                  <span className="font-semibold text-indigo-400">{statusText}</span>
                  <span className="font-mono text-white font-bold">{progress}%</span>
                </div>
                <div className="w-full bg-slate-800 rounded-full h-2 overflow-hidden">
                  <div 
                    className="bg-gradient-to-r from-indigo-500 to-emerald-400 h-2 rounded-full transition-all duration-300"
                    style={{ width: `${progress}%` }}
                  />
                </div>
              </div>
            )}

            {/* Preset High-DA Catalog Preview */}
            <div className="border-t border-slate-800/80 pt-4">
              <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-3">High-DA Verified Submission Target Platforms</h4>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                {[
                  { domain: 'medium.com', da: 95, cat: 'Web 2.0' },
                  { domain: 'crunchbase.com', da: 91, cat: 'Directory' },
                  { domain: 'producthunt.com', da: 90, cat: 'Tech' },
                  { domain: 'digitaljournal.com', da: 87, cat: 'PR Syndicate' },
                  { domain: 'clutch.co', da: 89, cat: 'B2B Catalog' },
                  { domain: 'nih.gov.citation', da: 94, cat: 'Edu Citation' }
                ].map((p, idx) => (
                  <div key={idx} className="bg-slate-950/60 p-2.5 rounded-lg border border-slate-800 flex items-center justify-between">
                    <div>
                      <p className="text-xs font-semibold text-white">{p.domain}</p>
                      <p className="text-[10px] text-slate-400">{p.cat}</p>
                    </div>
                    <span className="px-2 py-0.5 bg-emerald-500/20 text-emerald-400 text-[10px] font-mono rounded font-bold">
                      DA {p.da}
                    </span>
                  </div>
                ))}
              </div>
            </div>

          </div>

          {/* Sidebar Tips & Best Practices */}
          <div className="space-y-4">
            <div className="bg-gradient-to-b from-slate-900 to-indigo-950/40 p-5 rounded-2xl border border-slate-800 space-y-4">
              <h3 className="text-sm font-bold text-white flex items-center space-x-2">
                <ShieldCheck className="w-4 h-4 text-emerald-400" />
                <span>Google & Bing Link Safety Rules</span>
              </h3>
              
              <ul className="space-y-2 text-xs text-slate-300">
                <li className="flex items-start space-x-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                  <span>Maintain a <strong>70% Dofollow / 30% Nofollow</strong> ratio for natural Google indexing.</span>
                </li>
                <li className="flex items-start space-x-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                  <span>Vary anchor texts between <strong>Brand Names</strong> and <strong>Target Keywords</strong>.</span>
                </li>
                <li className="flex items-start space-x-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                  <span>RankPulse Pro auto-pings fast indexers to index backlinks within 24-48 hours.</span>
                </li>
              </ul>
            </div>

            <div className="bg-slate-900/90 p-5 rounded-2xl border border-slate-800 space-y-3">
              <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider">Anchor Text Diversity</h3>
              
              <div className="space-y-2">
                <div>
                  <div className="flex justify-between text-xs text-slate-400 mb-1">
                    <span>Brand Anchors ({client.name})</span>
                    <span className="font-semibold text-white">45%</span>
                  </div>
                  <div className="w-full bg-slate-800 rounded-full h-1.5">
                    <div className="bg-blue-500 h-1.5 rounded-full" style={{ width: '45%' }}></div>
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-xs text-slate-400 mb-1">
                    <span>Exact Target Keywords</span>
                    <span className="font-semibold text-white">35%</span>
                  </div>
                  <div className="w-full bg-slate-800 rounded-full h-1.5">
                    <div className="bg-indigo-500 h-1.5 rounded-full" style={{ width: '35%' }}></div>
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-xs text-slate-400 mb-1">
                    <span>Naked URLs ({client.domain})</span>
                    <span className="font-semibold text-white">20%</span>
                  </div>
                  <div className="w-full bg-slate-800 rounded-full h-1.5">
                    <div className="bg-emerald-500 h-1.5 rounded-full" style={{ width: '20%' }}></div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
      )}

      {/* TAB 2: LINK PROFILE DATA TABLE */}
      {selectedTab === 'profile' && (
        <div className="bg-slate-900/90 rounded-2xl border border-slate-800 p-6 space-y-4">
          
          {/* Controls Bar */}
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center space-x-2 w-full sm:w-auto">
              <div className="relative flex-1 sm:w-64">
                <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
                <input
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Search domain or anchor..."
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl pl-9 pr-3 py-2 text-xs text-white focus:outline-none focus:border-indigo-500"
                />
              </div>

              <select
                value={filterCategory}
                onChange={(e) => setFilterCategory(e.target.value)}
                className="bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-indigo-500"
              >
                <option value="all">All Categories</option>
                <option value="web 2.0">Web 2.0 Blogs</option>
                <option value="tech directory">Tech Directories</option>
                <option value="edu/gov">Edu / Gov Citations</option>
                <option value="press release">Press Release Syndicates</option>
                <option value="toxic">Toxic Links (&gt;50 Toxicity)</option>
              </select>
            </div>

            <button
              onClick={() => setSelectedTab('generator')}
              className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-semibold flex items-center space-x-1.5"
            >
              <Plus className="w-4 h-4" />
              <span>Add New Backlink</span>
            </button>
          </div>

          {/* Table */}
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-slate-800 text-[11px] font-semibold text-slate-400 uppercase tracking-wider bg-slate-950/60">
                  <th className="py-3 px-4">Referring Domain</th>
                  <th className="py-3 px-4">Domain Rating</th>
                  <th className="py-3 px-4">Anchor Text</th>
                  <th className="py-3 px-4">Category</th>
                  <th className="py-3 px-4">Link Type</th>
                  <th className="py-3 px-4">Status</th>
                  <th className="py-3 px-4">Toxicity</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60 text-xs">
                {filteredBacklinks.length === 0 ? (
                  <tr>
                    <td colSpan={7} className="py-8 text-center text-slate-400">
                      No backlinks found matching your filter criteria.
                    </td>
                  </tr>
                ) : (
                  filteredBacklinks.map((bl) => (
                    <tr key={bl.id} className="hover:bg-slate-800/40 transition">
                      <td className="py-3.5 px-4">
                        <div className="font-bold text-white flex items-center space-x-1.5">
                          <span>{bl.referringDomain}</span>
                          <a href={`https://${bl.referringDomain}`} target="_blank" rel="noreferrer" className="text-slate-400 hover:text-indigo-400">
                            <ExternalLink className="w-3 h-3" />
                          </a>
                        </div>
                        <p className="text-[11px] text-slate-400 truncate max-w-xs">{bl.referringPageTitle}</p>
                      </td>

                      <td className="py-3.5 px-4">
                        <span className="px-2.5 py-1 bg-indigo-500/20 text-indigo-300 font-mono font-bold rounded-lg border border-indigo-500/30 text-xs">
                          DR {bl.domainRating}
                        </span>
                      </td>

                      <td className="py-3.5 px-4 font-medium text-slate-200">
                        "{bl.anchorText}"
                      </td>

                      <td className="py-3.5 px-4 text-slate-300">
                        {bl.category}
                      </td>

                      <td className="py-3.5 px-4">
                        <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${
                          bl.linkType === 'dofollow' 
                            ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30'
                            : 'bg-slate-800 text-slate-400'
                        }`}>
                          {bl.linkType}
                        </span>
                      </td>

                      <td className="py-3.5 px-4">
                        <span className={`px-2 py-0.5 rounded text-[10px] font-semibold flex items-center space-x-1 w-fit ${
                          bl.status === 'indexed' ? 'bg-emerald-500/20 text-emerald-400' :
                          bl.status === 'pinged' ? 'bg-amber-500/20 text-amber-400' : 'bg-blue-500/20 text-blue-400'
                        }`}>
                          <span className="w-1.5 h-1.5 rounded-full bg-current"></span>
                          <span className="capitalize">{bl.status}</span>
                        </span>
                      </td>

                      <td className="py-3.5 px-4">
                        {bl.toxicityScore > 50 ? (
                          <span className="px-2 py-0.5 bg-rose-500/20 text-rose-400 border border-rose-500/30 rounded text-[10px] font-bold">
                            High Risk ({bl.toxicityScore}%)
                          </span>
                        ) : (
                          <span className="text-slate-400 text-xs">Safe ({bl.toxicityScore}%)</span>
                        )}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* TAB 3: AI COLD OUTREACH */}
      {selectedTab === 'outreach' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          
          {/* Opportunities Table */}
          <div className="lg:col-span-2 bg-slate-900/90 p-6 rounded-2xl border border-slate-800 space-y-4">
            <div>
              <h2 className="text-lg font-bold text-white flex items-center space-x-2">
                <Mail className="w-5 h-5 text-indigo-400" />
                <span>AI Backlink Guest Post & Citation Outreach Opportunities</span>
              </h2>
              <p className="text-xs text-slate-400 mt-1">
                Discovered high Domain Authority niche blogs accepting guest articles or editorial link insertions in {client.industry}.
              </p>
            </div>

            <div className="space-y-3">
              {outreachOps.map((op) => (
                <div key={op.id} className="bg-slate-950 p-4 rounded-xl border border-slate-800 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                  <div>
                    <div className="flex items-center space-x-2">
                      <h4 className="text-sm font-bold text-white">{op.websiteName}</h4>
                      <span className="px-2 py-0.5 bg-emerald-500/20 text-emerald-400 text-[10px] font-mono font-bold rounded">
                        DA {op.domainAuthority}
                      </span>
                    </div>
                    <p className="text-xs text-slate-400 mt-0.5">{op.niche} • ~{op.estimatedTraffic.toLocaleString()} monthly visits</p>
                    <p className="text-xs text-indigo-300 font-medium mt-1">Suggested Topic: "{op.suggestedTopic}"</p>
                  </div>

                  <button
                    onClick={() => handleGeneratePitch(op)}
                    className="px-4 py-2 bg-gradient-to-r from-indigo-600 to-blue-600 hover:from-indigo-500 hover:to-blue-500 text-white rounded-xl text-xs font-semibold flex items-center space-x-1.5 shadow-md shrink-0"
                  >
                    <Sparkles className="w-3.5 h-3.5" />
                    <span>Generate Pitch Email</span>
                  </button>
                </div>
              ))}
            </div>
          </div>

          {/* Generated Pitch Modal / Sidebar */}
          <div className="bg-slate-900/90 p-6 rounded-2xl border border-slate-800 space-y-4">
            <h3 className="text-sm font-bold text-white flex items-center space-x-2">
              <FileCode className="w-4 h-4 text-indigo-400" />
              <span>AI Outreach Pitch Composer</span>
            </h3>

            {activePitch ? (
              <div className="space-y-3">
                <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 text-xs text-slate-300 font-mono whitespace-pre-wrap max-h-96 overflow-y-auto">
                  {activePitch.email}
                </div>

                <button
                  onClick={handleCopyPitch}
                  className="w-full py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold flex items-center justify-center space-x-2 transition"
                >
                  {copied ? (
                    <>
                      <Check className="w-4 h-4 text-emerald-400" />
                      <span>Copied Pitch Email to Clipboard!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4" />
                      <span>Copy Email Pitch</span>
                    </>
                  )}
                </button>
              </div>
            ) : (
              <div className="p-8 text-center text-slate-500 text-xs">
                Click "Generate Pitch Email" on any outreach target to compose a customized pitch email.
              </div>
            )}
          </div>

        </div>
      )}

      {/* TAB 4: DISAVOW TOXIC LINKS */}
      {selectedTab === 'disavow' && (
        <div className="bg-slate-900/90 p-6 rounded-2xl border border-slate-800 space-y-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div>
              <h2 className="text-lg font-bold text-white flex items-center space-x-2">
                <AlertTriangle className="w-5 h-5 text-rose-400" />
                <span>Google Search Console Disavow Tool Generator</span>
              </h2>
              <p className="text-xs text-slate-400 mt-1">
                Protect your domain from Google manual action penalties by exporting a formatted `disavow.txt` file for low-quality spam PBNs.
              </p>
            </div>

            <button
              onClick={handleDownloadDisavow}
              className="px-4 py-2.5 bg-rose-600 hover:bg-rose-500 text-white rounded-xl text-xs font-bold flex items-center space-x-2 shadow-lg shadow-rose-600/30"
            >
              <Download className="w-4 h-4" />
              <span>Download disavow.txt</span>
            </button>
          </div>

          <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 font-mono text-xs text-slate-300 space-y-2">
            <p className="text-slate-500">// Preview of generated Google Search Console disavow file:</p>
            <pre className="text-emerald-400 whitespace-pre-wrap">{disavowContent}</pre>
          </div>
        </div>
      )}

    </div>
  );
};
